SELECT * FROM CUSTOMER;
SELECT * FROM INVOICE;
SELECT CONCAT(FIRST_NAME," ",LAST_NAME)AS CUSTOMER_FULL_NAME,C.CUSTOMER_ID,
SUM(TOTAL) AS MOST_SPENT_MONEY 
FROM CUSTOMER C JOIN INVOICE I 
ON C.CUSTOMER_ID=I.CUSTOMER_ID 
GROUP BY CUSTOMER_FULL_NAME,C.CUSTOMER_ID ORDER BY MOST_SPENT_MONEY DESC LIMIT 1;
