
/*Q2: Determine the most popular music genre for each country based on purchases.
o Hint: Use a CTE or window function to rank genres by purchase count per
country.*/

WITH GENRE_RANK AS 
(
SELECT C.COUNTRY, G.NAME AS GENRE_NAME,COUNT(T.TRACK_ID) AS TRACKS_SOLD,
DENSE_RANK() OVER(PARTITION BY C.COUNTRY ORDER BY COUNT(T.TRACK_ID) DESC)AS RNK_NAME FROM CUSTOMER C
JOIN INVOICE I ON C.CUSTOMER_ID=I.CUSTOMER_ID
JOIN INVOICE_LINE ON I.INVOICE_ID=IL.INVOICE_ID
JOIN TRACK T ON IL.TRACK_ID=T.TRACK_ID
JOIN GENRE G ON T.GENRE_ID=G.GENRE_ID
GROUP BY C.COUNTRY,G.NAME
)
SELECT COUNTRY, GENRE_NAME,TRACKS_SOLD FROM GENRE_RANK WHERE RNK_NAME=1 ORDER BY COUNTRY;