WITH ARTIST_EARNINGS AS(
SELECT C.CUSTOMER_ID,AR.ARTIST_ID,SUM(IL.UNIT_PRICE*IL.QUANTITY)AS TOTAL_CUSTOMER_REVENUE 
FROM CUSTOMER C JOIN INVOICE I ON C.CUSTOMER_ID=I.CUSTOMER_ID
JOIN INVOICE_LINE IL ON I.INVOICE_ID=IL.INVOICE_ID
JOIN TRACK T ON IL.TRACK_ID=T.TRACK_ID
JOIN ALBUM AL ON T.ALBUM_ID=AL.ALBUM_ID
JOIN ARTIST AR ON AL.ARTIST_ID=AR.ARTIST_ID
GROUP BY C.CUSTOMER_ID,AR.ARTIST_ID)
SELECT *FROM ARTIST_EARNINGS ORDER BY CUSTOMER_ID,ARTIST_ID;