SELECT * FROM CUSTOMER;
SELECT *FROM INVOICE;
SELECT *FROM INVOICE_LINE;

/*Q3: Identify the top-spending customer for each country.
o Hint: Calculate the total spending per customer per country and filter for the
highest spending*/

WITH CUSTOMER_SPENDING AS
(
SELECT C.CUSTOMER_ID, C.COUNTRY, SUM(I.TOTAL) AS TOTAL_SPENT,
DENSE_RANK()OVER(PARTITION BY C.COUNTRY ORDER BY SUM(I.TOTAL)DESC) AS RNK_NAME 
FROM CUSTOMER C JOIN INVOICE I ON C.CUSTOMER_ID=I.CUSTOMER_ID 
JOIN INVOICE_LINE IL ON I.INVOICE_ID=IL.INVOICE_ID 
GROUP BY C.CUSTOMER_ID, C.COUNTRY 
)
SELECT CUSTOMER_ID,COUNTRY,TOTAL_SPENT FROM CUSTOMER_SPENDING WHERE RNK_NAME=1 ORDER BY COUNTRY DESC;

