SELECT C.EMAIL, C.FIRST_NAME, C.LAST_NAME FROM CUSTOMER C 
JOIN INVOICE I ON C.CUSTOMER_ID= I.CUSTOMER_ID 
JOIN INVOICE_LINE IL ON I.INVOICE_ID=IL.INVOICE_ID
JOIN TRACK T ON IL.TRACK_ID=T.TRACK_ID
JOIN GENRE G ON T.GENRE_ID= G.GENRE_ID
WHERE G.NAME= "ROCK";
